// Données des 20 posts photo. Le texte à l'image reste court ; la promesse est dans chaque légende.
// Markup : *mot* = doré à l'image.
export type PhotoPost = {
	slug: string;
	photo: string; // public/photos/xx.png
	template: 'full' | 'letterbox' | 'bigtype' | 'subtitle' | 'quiet';
	kicker: string;
	line?: string;
	focus?: string; // object-position
	caption: string;
};

const SIGN = '\n\nVision. On accompagne les restaurants de Suisse romande à devenir des références.\nUn restaurant par cuisine, par ville.';
const CTA = '\n\nVotre place est peut-être encore libre : message privé.';
const X3 = 'Les restaurants qu’on accompagne : ×3 clients en moins de 90 jours, +50 % de chiffre d’affaires, plus de 500 000 personnes touchées.';
const GALATA = 'Dernier restaurant accompagné : 12 000 personnes touchées en 30 jours avec quatre vidéos, une portée multipliée par 16, des visites de profil multipliées par 6.';

export const photoPosts: PhotoPost[] = [
	{slug: 'POV', photo: '01.png', template: 'subtitle', kicker: 'Coulisses', line: 'POV : votre restaurant devient celui dont tout le monde parle.', caption: `POV : votre restaurant devient celui dont tout le monde parle.\n\nOn ne vend pas des vidéos. On accompagne votre restaurant, semaine après semaine, jusqu’à ce que la salle soit pleine et que les gens le recommandent. ${X3}${SIGN}${CTA}`},
	{slug: 'Facade', photo: '02.png', template: 'bigtype', kicker: 'Fribourg · 19h', line: 'PLUS DE\nCLIENTS.\nEN 90\nJOURS.', caption: `Plus de clients. En 90 jours.\n\nÀ 19h, les gens décident où ils vont manger, téléphone en main. Un bon restaurant que personne ne connaît reste un bon restaurant vide.\n\nNotre travail, c’est l’inverse. ${X3}${SIGN}${CTA}`},
	{slug: 'Table', photo: '03.png', template: 'full', kicker: '21h14 · Un mardi', line: 'Une salle pleine un mardi. C’est là qu’on vous emmène, *en moins de 90 jours.*', caption: `Une salle pleine un mardi. C’est là qu’on vous emmène, en moins de 90 jours.\n\nPas des vues, pas des likes : des couverts, des habitués, une équipe fière de sa salle. ${X3}\n\nComment ? On travaille avec vous chaque semaine : on filme votre vrai service, on publie, on mesure, on ajuste.${SIGN}${CTA}`},
	{slug: 'Menu', photo: '04.png', template: 'full', kicker: 'Point de vue', line: 'On ne vend pas des vidéos. On fait de votre restaurant *une adresse qu’on recommande.*', caption: `On ne vend pas des vidéos. On fait de votre restaurant une adresse qu’on recommande.\n\nPas besoin de montrer un visage pour donner envie. Il faut montrer une soirée que les gens ont envie de vivre, à l’heure où ils choisissent leur table.\n\n${GALATA}${SIGN}${CTA}`},
	{slug: 'Chefs', photo: '05.png', template: 'full', kicker: 'Exclusivité', line: 'Deux chefs. Une ville. *Un seul* qu’on accompagne.', caption: `Deux chefs. Une ville. Un seul qu’on accompagne.\n\nOn n’accompagne jamais deux restaurants de la même cuisine dans la même ville. Votre croissance, votre quartier, vos clients : on ne les partage avec personne. Le premier qui signe garde la place.${SIGN}${CTA}`},
	{slug: 'Patron', photo: '06.png', template: 'full', kicker: 'Trente ans de métier', line: 'Trente ans de métier. Il méritait qu’on *le fasse connaître.*', caption: `Trente ans de métier. Il méritait qu’on le fasse connaître.\n\nChaque restaurant a une histoire que ses futurs clients ne connaissent pas encore. La raconter, la montrer, la répéter : c’est ce qui fait passer une bonne adresse au rang de référence. ${X3}${SIGN}${CTA}`},
	{slug: 'Geste', photo: '07.png', template: 'full', kicker: 'Le geste', line: 'Ce geste, personne ne le voyait. On l’a montré à *500 000 personnes.*', caption: `Ce geste, personne ne le voyait. On l’a montré à 500 000 personnes.\n\nLe service, la découpe, le dressage : tout ce qui se passe à trois mètres des tables et qui donne envie de venir. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Pain', photo: '08.png', template: 'letterbox', kicker: 'Mains', line: 'Quatre vidéos. Trente jours. *12 000 personnes* qui ont faim.', caption: `Quatre vidéos. Trente jours. 12 000 personnes qui ont faim.\n\nLa différence entre une photo de plat et une vidéo qui fait réserver tient dans un geste. Et la différence entre une vidéo et un restaurant plein tient dans l’accompagnement qui suit. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Moniteur', photo: '09.png', template: 'quiet', kicker: 'Coulisses · Prise 3', caption: `Prise 3.\n\nCe que voit notre moniteur pendant que vous cuisinez. Vous ne changez rien à votre service : on s’adapte à vous, pas l’inverse.\n\nUne matinée chez vous, puis un accompagnement chaque semaine jusqu’à ce que la salle soit pleine. ${X3}${SIGN}${CTA}`},
	{slug: 'Avant', photo: '10.png', template: 'full', kicker: '10h12', line: 'Avant le service, on travaille avec vous. Après, *vous refusez du monde.*', caption: `Avant le service, on travaille avec vous. Après, vous refusez du monde.\n\nLa salle vide, la lumière qui entre, les tables prêtes. C’est là qu’on commence, pour que le soir vous soyez pleins. ${X3}${SIGN}${CTA}`},
	{slug: 'Lausanne', photo: '11.png', template: 'bigtype', kicker: 'Lausanne · Terrasse', line: '×3\nCLIENTS.\nMOINS DE\n90 JOURS.', caption: `×3 clients. Moins de 90 jours.\n\nC’est ce que les restaurants qu’on accompagne constatent en salle, pas sur un tableau de bord. +50 % de chiffre d’affaires, plus de 500 000 personnes touchées. Le seul chiffre qui compte se lit dans votre salle le vendredi soir.${SIGN}${CTA}`},
	{slug: 'Fondue', photo: '12.png', template: 'full', kicker: 'Suisse', line: 'On connaît la seconde où le fromage file. Et celle où *le client réserve.*', caption: `On connaît la seconde où le fromage file. Et celle où le client réserve.\n\nUn plat se filme comme un visage : il faut connaître le geste avant de lancer la caméra. On ne travaille qu’avec des restaurants, depuis le début. C’est ce qui nous permet de les faire grandir.${SIGN}${CTA}`},
	{slug: 'Arrivee', photo: '13.png', template: 'full', kicker: 'Coulisses', line: 'On arrive avant le coup de feu. On reste jusqu’à ce que *la salle soit pleine.*', caption: `On arrive avant le coup de feu. On reste jusqu’à ce que la salle soit pleine.\n\nUne équipe légère, une matinée, votre restaurant dans sa meilleure lumière. Puis un suivi chaque semaine. Vous ne fermez pas, vous ne jouez rien. ${X3}${SIGN}${CTA}`},
	{slug: 'Scene', photo: '14.png', template: 'bigtype', kicker: 'Scène 01 · Fribourg', line: '+50 %\nDE CHIFFRE\nD’AFFAIRES.', caption: `+50 % de chiffre d’affaires.\n\nScène 01 : le tournage. Scène 02 : la file devant votre porte. Un restaurant devient un plateau, le vôtre, tel qu’il est, un mardi matin. Puis on l’accompagne jusqu’à ce qu’il devienne une référence. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Serveur', photo: '15.png', template: 'subtitle', kicker: 'Film', line: '— Vous cuisinez. On s’occupe de faire venir le monde.', caption: `Vous cuisinez. On s’occupe de faire venir le monde.\n\nStratégie, tournage, diffusion, suivi des résultats chaque semaine : un seul interlocuteur, de l’idée à la salle pleine. ${X3}${SIGN}${CTA}`},
	{slug: 'Uniquement', photo: '16.png', template: 'bigtype', kicker: 'Positionnement', line: 'DE BONNE\nADRESSE À\nRÉFÉRENCE.', caption: `De bonne adresse à référence.\n\nOn ne travaille qu’avec des restaurants. Un seul métier, appris de l’intérieur, et une seule promesse : faire de votre restaurant celui dont on parle dans votre ville. ${X3}${SIGN}${CTA}`},
	{slug: 'Feu', photo: '17.png', template: 'full', kicker: '20h03 · Le passe', line: 'Le coup de feu, filmé à 120 images par seconde. Vu *16 fois plus.*', caption: `Le coup de feu, filmé à 120 images par seconde. Vu 16 fois plus.\n\nCe que vos clients adorent et que personne ne montre. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Dessert', photo: '18.png', template: 'letterbox', kicker: 'Dernière assiette', line: 'Le dessert n’attend pas. *Vos futurs clients* non plus.', caption: `Le dessert n’attend pas. Vos futurs clients non plus.\n\nOn connaît la seconde où la croûte craque, et l’heure où les gens réservent. C’est notre métier d’en faire une habitude dans votre salle. ${X3}${SIGN}${CTA}`},
	{slug: 'Rire', photo: '19.png', template: 'full', kicker: 'Ce qu’on construit', line: 'Ce qu’on construit avec vous : des soirées comme ça, *toutes les semaines.*', caption: `Ce qu’on construit avec vous : des soirées comme ça, toutes les semaines.\n\nPas des vidéos. Une salle pleine, des habitués qui reviennent, des nouveaux qui découvrent, une équipe fière. ${X3}${SIGN}${CTA}`},
	{slug: 'Plateau', photo: '20.png', template: 'full', kicker: 'Candidatures ouvertes', line: 'On ne vous livre pas des vidéos. On vous accompagne jusqu’à *trois fois plus de clients.*', caption: `On ne vous livre pas des vidéos. On vous accompagne jusqu’à trois fois plus de clients.\n\nOn arrive avant le service, on repart avant le coup de feu, et on reste à vos côtés chaque semaine. ${X3}\n\nUn seul restaurant par cuisine, par ville. Candidatures ouvertes.${SIGN}${CTA}`},
];
