// Données des 20 posts photo. Le texte à l'image reste court ; la promesse est dans chaque légende.
// Markup : *mot* = doré à l'image.
export type PhotoPost = {
	slug: string;
	photo: string; // public/photos/xx.png
	template: 'full' | 'letterbox' | 'bigtype' | 'subtitle' | 'quiet' | 'minimal';
	short?: string; // version minimale : 2 à 5 mots
	kicker: string;
	line?: string;
	focus?: string; // object-position
	caption: string;
};

const SIGN = '\n\nVision. On accompagne les restaurants de Suisse romande sur la durée, jusqu’à ce qu’ils deviennent des références.\nUn restaurant par cuisine, par ville.';
const CTA = '\n\nVotre place est peut-être encore libre : message privé.';
const X3 = 'Les restaurants qu’on accompagne : ×3 clients en moins de 90 jours, +50 % de chiffre d’affaires. Ce qu’on coûte revient en couverts dès le premier mois.';
const LONG = 'On ne vient pas une fois. On revient chaque semaine : tournages réguliers chez vous, publication, mesure, ajustements. Et vous gardez le contrôle sur tout depuis votre app Vision : tournages planifiés, vidéos à valider, résultats en direct.';
const GALATA = 'Dernier restaurant accompagné : 12 000 personnes touchées en 30 jours, une portée multipliée par 16, des visites de profil multipliées par 6.';

export const photoPosts: PhotoPost[] = [
	{slug: 'POV', photo: '01.png', short: 'Votre restaurant. En film.', template: 'subtitle', kicker: 'Coulisses', line: 'POV : votre restaurant devient celui dont tout le monde parle.', caption: `POV : votre restaurant devient celui dont tout le monde parle.\n\n${LONG} ${X3}${SIGN}${CTA}`},
	{slug: 'Facade', photo: '02.png', short: 'Plus de clients.', template: 'bigtype', kicker: 'Fribourg · 19h', line: 'PLUS DE\nCLIENTS.\nMOIS APRÈS\nMOIS.', caption: `Plus de clients. Mois après mois.\n\nÀ 19h, les gens décident où ils vont manger, téléphone en main. Un bon restaurant que personne ne connaît reste un bon restaurant vide.\n\nNotre travail, c’est l’inverse, et on le fait avec vous sur la durée. ${X3}${SIGN}${CTA}`},
	{slug: 'Table', photo: '03.png', short: 'Un mardi. Salle pleine.', template: 'full', kicker: '21h14 · Un mardi', line: 'Une salle pleine un mardi. C’est ce qu’on construit avec vous, *semaine après semaine.*', caption: `Une salle pleine un mardi. C’est ce qu’on construit avec vous, semaine après semaine.\n\nPas des vues, pas des likes : des couverts, des habitués, une équipe fière de sa salle. ${X3}\n\n${LONG}${SIGN}${CTA}`},
	{slug: 'Menu', photo: '04.png', short: 'On donne faim.', template: 'full', kicker: 'Point de vue', line: 'On ne vend pas des vidéos. On fait de votre restaurant *une adresse qu’on recommande.*', caption: `On ne vend pas des vidéos. On fait de votre restaurant une adresse qu’on recommande.\n\nPas besoin de montrer un visage pour donner envie. Il faut montrer une soirée que les gens ont envie de vivre, à l’heure où ils choisissent leur table. Et le montrer chaque semaine, pas une fois.\n\n${GALATA}${SIGN}${CTA}`},
	{slug: 'Chefs', photo: '05.png', short: 'Un seul par ville.', template: 'full', kicker: 'Exclusivité', line: 'Deux chefs. Une ville. *Un seul* qu’on accompagne.', caption: `Deux chefs. Une ville. Un seul qu’on accompagne.\n\nOn n’accompagne jamais deux restaurants de la même cuisine dans la même ville. Votre croissance, votre quartier, vos clients : on ne les partage avec personne, et on reste à vos côtés sur la durée. Le premier qui signe garde la place.${SIGN}${CTA}`},
	{slug: 'Patron', photo: '06.png', short: 'Trente ans de métier.', template: 'full', kicker: 'Trente ans de métier', line: 'Trente ans de métier. Il méritait un partenaire *sur la durée.*', caption: `Trente ans de métier. Il méritait un partenaire sur la durée.\n\nChaque restaurant a une histoire que ses futurs clients ne connaissent pas encore. La raconter une fois ne suffit pas : on revient, on la montre semaine après semaine, jusqu’à ce que l’adresse devienne une référence. ${X3}${SIGN}${CTA}`},
	{slug: 'Geste', photo: '07.png', short: 'Le geste.', template: 'full', kicker: 'Le geste', line: 'Ce geste, personne ne le voyait. On l’a montré à *500 000 personnes.*', caption: `Ce geste, personne ne le voyait. On l’a montré à 500 000 personnes.\n\nLe service, la découpe, le dressage : tout ce qui se passe à trois mètres des tables et qui donne envie de venir. On revient le filmer régulièrement, parce qu’un restaurant change chaque semaine. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Pain', photo: '08.png', short: '12 000 personnes. 30 jours.', template: 'letterbox', kicker: 'Mains', line: 'Trente jours. *12 000 personnes* qui ont faim.', caption: `Trente jours. 12 000 personnes qui ont faim.\n\nLa différence entre une photo de plat et une vidéo qui fait réserver tient dans un geste. Et la différence entre une vidéo et un restaurant plein tient dans l’accompagnement qui suit, mois après mois. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Moniteur', photo: '09.png', short: 'Vous validez tout.', template: 'full', kicker: 'Votre app Vision', line: 'Vous voyez tout. Vous validez tout. *Depuis votre app.*', caption: `Vous voyez tout. Vous validez tout. Depuis votre app.\n\nLes tournages planifiés chez vous, chaque vidéo avant publication, vos chiffres en direct. Vous ne changez rien à votre service, on s’adapte à vous, et vous gardez la main sur tout.\n\n${LONG} ${X3}${SIGN}${CTA}`},
	{slug: 'Avant', photo: '10.png', short: 'Avant le service.', template: 'full', kicker: '10h12', line: 'On revient chaque semaine. Jusqu’à ce que *vous refusiez du monde.*', caption: `On revient chaque semaine. Jusqu’à ce que vous refusiez du monde.\n\nLa salle vide, la lumière qui entre, les tables prêtes. C’est là qu’on commence. Puis on revient tourner, on publie, on mesure, on ajuste, pour que le soir vous soyez pleins. ${X3}${SIGN}${CTA}`},
	{slug: 'Lausanne', photo: '11.png', short: '×3 clients. 90 jours.', template: 'bigtype', kicker: 'Lausanne · Terrasse', line: '×3\nCLIENTS.\nMOINS DE\n90 JOURS.', caption: `×3 clients. Moins de 90 jours.\n\nC’est ce que les restaurants qu’on accompagne constatent en salle, pas sur un tableau de bord. +50 % de chiffre d’affaires : ce qu’on coûte revient en couverts dès le premier mois, et on continue mois après mois.${SIGN}${CTA}`},
	{slug: 'Fondue', photo: '12.png', short: 'La seconde juste.', template: 'full', kicker: 'Suisse', line: 'On connaît la seconde où le fromage file. Et celle où *le client réserve.*', caption: `On connaît la seconde où le fromage file. Et celle où le client réserve.\n\nUn plat se filme comme un visage : il faut connaître le geste avant de lancer la caméra. On ne travaille qu’avec des restaurants, depuis le début, et on reste avec eux sur la durée.${SIGN}${CTA}`},
	{slug: 'Arrivee', photo: '13.png', short: 'On revient.', template: 'full', kicker: 'Coulisses', line: 'On ne vient pas une fois. *On revient.*', caption: `On ne vient pas une fois. On revient.\n\nUne équipe légère, chez vous, plusieurs fois par mois. Avant le service, pendant, après. Vous ne fermez pas, vous ne jouez rien. ${LONG} ${X3}${SIGN}${CTA}`},
	{slug: 'Scene', photo: '14.png', short: '+50 % de chiffre.', template: 'bigtype', kicker: 'Scène 01 · Fribourg', line: '+50 %\nDE CHIFFRE\nD’AFFAIRES.', caption: `+50 % de chiffre d’affaires.\n\nC’est ce que constatent les restaurants qu’on accompagne. Ce qu’on coûte revient en couverts dès le premier mois, le reste est pour vous. Un restaurant devient un plateau, le vôtre, tel qu’il est, et on y revient chaque semaine. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Serveur', photo: '15.png', short: 'Vous cuisinez.', template: 'subtitle', kicker: 'Film', line: '— Vous cuisinez. On s’occupe du reste, *tous les mois.*', caption: `Vous cuisinez. On s’occupe du reste, tous les mois.\n\nStratégie, tournages réguliers, diffusion, suivi des résultats chaque semaine : un seul interlocuteur, sur la durée, de l’idée à la salle pleine. Et tout est visible dans votre app : ce qui est prévu, ce qui est publié, ce que ça rapporte. ${X3}${SIGN}${CTA}`},
	{slug: 'Uniquement', photo: '16.png', short: 'De bonne adresse à référence.', template: 'full', kicker: 'Positionnement · 23h40', line: 'De bonne adresse à *référence.* C’est un chemin, on le fait avec vous.', caption: `De bonne adresse à référence. C’est un chemin, on le fait avec vous.\n\nOn ne travaille qu’avec des restaurants. Un seul métier, appris de l’intérieur, et une seule promesse : faire grandir votre restaurant, mois après mois, jusqu’à ce qu’on en parle dans toute la ville. ${X3}${SIGN}${CTA}`},
	{slug: 'Feu', photo: '17.png', short: 'Le coup de feu.', template: 'full', kicker: '20h03 · Le passe', line: 'Le coup de feu, filmé à 120 images par seconde. Vu *16 fois plus.*', caption: `Le coup de feu, filmé à 120 images par seconde. Vu 16 fois plus.\n\nCe que vos clients adorent et que personne ne montre. Nous, on revient le filmer chaque semaine. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Dessert', photo: '18.png', short: 'Le dessert n’attend pas.', template: 'letterbox', kicker: 'Dernière assiette', line: 'Le dessert n’attend pas. *Vos futurs clients* non plus.', focus: '50% 70%', caption: `Le dessert n’attend pas. Vos futurs clients non plus.\n\nOn connaît la seconde où la croûte craque, et l’heure où les gens réservent. Notre métier, c’est d’en faire une habitude dans votre salle, semaine après semaine. ${X3}${SIGN}${CTA}`},
	{slug: 'Rire', photo: '19.png', short: 'Toutes les semaines.', template: 'full', kicker: 'Ce qu’on construit', line: 'Ce qu’on construit avec vous : des soirées comme ça, *toutes les semaines.*', caption: `Ce qu’on construit avec vous : des soirées comme ça, toutes les semaines.\n\nPas des vidéos. Une salle pleine, des habitués qui reviennent, des nouveaux qui découvrent, une équipe fière. Et un partenaire qui revient chaque semaine pour que ça dure. ${X3}${SIGN}${CTA}`},
	{slug: 'Plateau', photo: '20.png', short: 'Candidatures ouvertes.', template: 'full', kicker: 'Candidatures ouvertes', line: 'On ne vous livre pas des vidéos. On est chez vous *tous les mois*, jusqu’à ×3 clients.', caption: `On ne vous livre pas des vidéos. On est chez vous tous les mois, jusqu’à ×3 clients.\n\n${LONG} ${X3}\n\nUn seul restaurant par cuisine, par ville. Candidatures ouvertes.${SIGN}${CTA}`},
];
