// Données des 20 posts photo. Le texte à l'image reste court ; la promesse est dans chaque légende.
// Markup : *mot* = doré à l'image.
export type PhotoPost = {
	slug: string;
	photo: string; // public/photos/xx.png
	template: 'full' | 'letterbox' | 'bigtype' | 'subtitle' | 'quiet';
	kicker: string;
	line?: string;
	focus?: string; // object-position
	caption: string;
};

const SIGN = '\n\nVision. Agence vidéo, restaurants uniquement, Suisse romande.\nUn restaurant par cuisine, par ville.';
const CTA = '\n\nVotre place est peut-être encore libre : message privé.';
const X3 = 'Nos restaurants partenaires : ×3 clients en moins de 90 jours, +50 % de chiffre d’affaires, plus de 500 000 personnes touchées.';
const GALATA = 'Dernier cas : 12 000 personnes touchées en 30 jours avec quatre vidéos, une portée multipliée par 16, des visites de profil multipliées par 6.';

export const photoPosts: PhotoPost[] = [
	{slug: 'POV', photo: '01.png', template: 'subtitle', kicker: 'Coulisses', line: 'POV : votre restaurant fait des films. Et la salle se remplit.', caption: `POV : votre restaurant fait des films. Et la salle se remplit.\n\nOn ne vend pas des vidéos. On vous accompagne pour aller chercher plus de clients, toutes les semaines. ${X3}${SIGN}${CTA}`},
	{slug: 'Facade', photo: '02.png', template: 'bigtype', kicker: 'Fribourg · 19h', line: 'PLUS DE\nCLIENTS.\nEN 90\nJOURS.', caption: `Plus de clients. En 90 jours.\n\nÀ 19h, les gens décident où ils vont manger, téléphone en main. Si votre restaurant n’est pas sur leur écran à ce moment-là, ils vont ailleurs.\n\nOn règle ça. ${X3}${SIGN}${CTA}`},
	{slug: 'Table', photo: '03.png', template: 'full', kicker: '21h14 · Un mardi', line: 'Une salle pleine un mardi. C’est ça qu’on livre en *moins de 90 jours.*', caption: `Une salle pleine un mardi. C’est ça qu’on livre.\n\nPas des vues, pas des likes : des couverts. ${X3}\n\nComment ? On filme votre vrai service, on publie chaque semaine, on ajuste jusqu’à ce que la salle soit pleine.${SIGN}${CTA}`},
	{slug: 'Menu', photo: '04.png', template: 'full', kicker: 'Point de vue', line: 'Chaque vidéo a un seul travail : *faire réserver.*', caption: `Chaque vidéo a un seul travail : faire réserver.\n\nPas besoin de montrer un visage pour donner faim. Il faut montrer une soirée que les gens ont envie de vivre, à l’heure où ils choisissent leur table.\n\n${GALATA}${SIGN}${CTA}`},
	{slug: 'Chefs', photo: '05.png', template: 'full', kicker: 'Exclusivité', line: 'Deux chefs. Une ville. *Une seule place* chez Vision.', caption: `Deux chefs. Une ville. Une seule place chez Vision.\n\nOn ne travaille jamais pour deux restaurants de la même cuisine dans la même ville. Vos clients, vos vidéos, votre quartier : on ne les partage avec personne. Le premier qui signe garde la place.${SIGN}${CTA}`},
	{slug: 'Patron', photo: '06.png', template: 'full', kicker: 'Trente ans de métier', line: 'Trente ans de métier. Il manquait *la caméra.*', caption: `Trente ans de métier. Il manquait la caméra.\n\nChaque restaurant a une histoire que ses futurs clients ne connaissent pas encore. La raconter, c’est ce qui remplit la salle. ${X3}${SIGN}${CTA}`},
	{slug: 'Geste', photo: '07.png', template: 'full', kicker: 'Le geste', line: 'Ce geste vaut plus qu’une pub. On l’a montré à *500 000 personnes.*', caption: `Ce geste vaut plus qu’une pub. On l’a montré à 500 000 personnes.\n\nLe service, la découpe, le dressage : tout ce qui se passe à trois mètres des tables et qui donne envie de venir. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Pain', photo: '08.png', template: 'letterbox', kicker: 'Mains', line: 'Quatre vidéos. Trente jours. *12 000 personnes* qui ont faim.', caption: `Quatre vidéos. Trente jours. 12 000 personnes qui ont faim.\n\nLa différence entre une photo de plat et une vidéo qui fait réserver tient dans un geste. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Moniteur', photo: '09.png', template: 'quiet', kicker: 'Coulisses · Prise 3', caption: `Prise 3.\n\nCe que voit notre moniteur pendant que vous cuisinez. Vous ne changez rien à votre service : on s’adapte à vous, pas l’inverse.\n\nUne matinée de tournage, un mois de contenu, une salle qui se remplit. ${X3}${SIGN}${CTA}`},
	{slug: 'Avant', photo: '10.png', template: 'full', kicker: '10h12', line: 'Avant le service, on tourne. Après, *vous refusez du monde.*', caption: `Avant le service, on tourne. Après, vous refusez du monde.\n\nLa salle vide, la lumière qui entre, les tables prêtes. C’est là qu’on filme, pour que le soir vous soyez pleins. ${X3}${SIGN}${CTA}`},
	{slug: 'Lausanne', photo: '11.png', template: 'bigtype', kicker: 'Lausanne · Terrasse', line: '×3\nCLIENTS.\nMOINS DE\n90 JOURS.', caption: `×3 clients. Moins de 90 jours.\n\nC’est ce que nos restaurants partenaires constatent en salle, pas sur un tableau de bord. +50 % de chiffre d’affaires, plus de 500 000 personnes touchées. Le seul chiffre qui compte se lit dans votre salle le vendredi soir.${SIGN}${CTA}`},
	{slug: 'Fondue', photo: '12.png', template: 'full', kicker: 'Suisse', line: 'On connaît la seconde où le fromage file. Et celle où *le client réserve.*', caption: `On connaît la seconde où le fromage file. Et celle où le client réserve.\n\nUn plat se filme comme un visage : il faut connaître le geste avant de lancer la caméra. On ne filme que des restaurants, depuis le début.${SIGN}${CTA}`},
	{slug: 'Arrivee', photo: '13.png', template: 'full', kicker: 'Coulisses', line: 'On arrive avant le coup de feu. On repart quand *la salle est pleine.*', caption: `On arrive avant le coup de feu. On repart quand la salle est pleine.\n\nUne équipe légère, une matinée, votre restaurant dans sa meilleure lumière. Vous ne fermez pas, vous ne jouez rien. ${X3}${SIGN}${CTA}`},
	{slug: 'Scene', photo: '14.png', template: 'bigtype', kicker: 'Scène 01 · Fribourg', line: '+50 %\nDE CHIFFRE\nD’AFFAIRES.', caption: `+50 % de chiffre d’affaires.\n\nScène 01 : le tournage. Scène 02 : la file devant votre porte.\n\nUn restaurant devient un plateau, le vôtre, tel qu’il est, un mardi matin. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Serveur', photo: '15.png', template: 'subtitle', kicker: 'Film', line: '— Vous cuisinez. On remplit la salle.', caption: `Vous cuisinez. On remplit la salle.\n\nStratégie, tournage, montage, publication, suivi des résultats : un seul interlocuteur, de l’idée à la salle pleine. ${X3}${SIGN}${CTA}`},
	{slug: 'Uniquement', photo: '16.png', template: 'bigtype', kicker: 'Positionnement', line: 'RESTAURANTS.\nUNIQUEMENT.', caption: `Restaurants. Uniquement.\n\nPas de mode, pas d’immobilier, pas de tech. Un seul métier, appris de l’intérieur, et une seule promesse : plus de clients dans votre salle. ${X3}${SIGN}${CTA}`},
	{slug: 'Feu', photo: '17.png', template: 'full', kicker: '20h03 · Le passe', line: 'Le coup de feu, filmé à 120 images par seconde. Vu *16 fois plus.*', caption: `Le coup de feu, filmé à 120 images par seconde. Vu 16 fois plus.\n\nCe que vos clients adorent et que personne ne filme. ${GALATA}${SIGN}${CTA}`},
	{slug: 'Dessert', photo: '18.png', template: 'letterbox', kicker: 'Dernière assiette', line: 'Le dessert n’attend pas. *Vos futurs clients* non plus.', caption: `Le dessert n’attend pas. Vos futurs clients non plus.\n\nOn connaît la seconde où la croûte craque, et l’heure où les gens réservent. C’est notre métier. ${X3}${SIGN}${CTA}`},
	{slug: 'Rire', photo: '19.png', template: 'full', kicker: 'Ce qu’on vend vraiment', line: 'Ce qu’on vend vraiment : des soirées comme ça, *toutes les semaines.*', caption: `Ce qu’on vend vraiment : des soirées comme ça, toutes les semaines.\n\nPas des vidéos. Une salle pleine, des habitués qui reviennent, des nouveaux qui découvrent. ${X3}${SIGN}${CTA}`},
	{slug: 'Plateau', photo: '20.png', template: 'full', kicker: 'Candidatures ouvertes', line: 'Une matinée de tournage. *Trois fois plus de clients* en 90 jours.', caption: `Une matinée de tournage. Trois fois plus de clients en 90 jours.\n\nOn arrive avant le service, on repart avant le coup de feu, et votre compte est nourri pour un mois. ${X3}\n\nUne seule place par cuisine, par ville. Candidatures ouvertes.${SIGN}${CTA}`},
];
