import type {DeckPage} from './Deck';

export const deck: DeckPage[] = [
	{kind: 'cover', photo: '03.png', title: 'On accompagne\nles restaurants\nà devenir des\nréférences.', sub: 'Vision · Suisse romande\nUn restaurant par cuisine, par ville.'},
	{kind: 'statement', kicker: 'Le constat', photo: '10.png', title: 'Un bon restaurant que\npersonne ne connaît reste\nun bon restaurant vide.', body: 'À 19h, vos futurs clients décident où ils vont manger, téléphone en main. Si votre salle n’est pas sur leur écran à ce moment-là, ils vont ailleurs.\n\nNotre travail, c’est l’inverse.'},
	{kind: 'numbers', kicker: 'Résultats', items: [{big: '×3', label: 'clients en moins de 90 jours chez les restaurants qu’on accompagne'}, {big: '+50 %', label: 'de chiffre d’affaires sur la même période'}, {big: '500 000', label: 'personnes touchées en Suisse romande'}], note: 'Dernier restaurant accompagné, Fribourg : 12 000 personnes touchées en 30 jours, portée ×16, visites de profil ×6, clics ×10. Résultats constatés en salle et sur les comptes des restaurants accompagnés.'},
	{kind: 'steps', kicker: 'L’accompagnement', title: 'Une matinée chez vous.\nPuis chaque semaine.', steps: [{n: '01', t: 'On arrive avant le service', d: 'Une équipe légère, votre restaurant dans sa meilleure lumière. Vous ne fermez pas, vous ne jouez rien.'}, {n: '02', t: 'On filme le vrai service', d: 'Le geste, la salle, l’heure. Pas de mise en scène : ce qui se passe déjà chez vous, montré comme personne ne le montre.'}, {n: '03', t: 'On publie, on mesure, on ajuste', d: 'Chaque semaine, un seul interlocuteur. On suit ce qui remplit la salle et on pousse ce qui marche.'}, {n: '04', t: 'Jusqu’à ce que la salle soit pleine', d: 'Le seul chiffre qui compte se lit dans votre salle le vendredi soir.'}]},
	{kind: 'photos', kicker: 'Ce qu’on montre', photos: ['07.png', '19.png', '17.png', '12.png', '08.png', '18.png']},
	{kind: 'statement', kicker: 'Exclusivité', photo: '05.png', title: 'Un restaurant par cuisine,\npar ville.', body: 'On n’accompagne jamais deux restaurants de la même cuisine dans la même ville. Votre croissance, votre quartier, vos clients : on ne les partage avec personne.\n\nLe premier qui signe garde la place.'},
	{kind: 'offer', kicker: 'Investissement', title: 'Ce que comprend\nl’accompagnement.', lines: ['Stratégie et positionnement de votre restaurant', 'Tournage chez vous, avant le service', 'Vidéos courtes montées, publiées, suivies chaque semaine', 'Suivi des résultats et ajustements', 'Exclusivité sur votre cuisine dans votre ville', 'Un seul interlocuteur, réponse en 24 heures'], price: '1 890.–', cta: 'Votre place est-elle libre ? · @vision.agency · visionmedia-agency.com'},
];
