import type {DeckPage} from './Deck';

export const deck: DeckPage[] = [
	{kind: 'cover', photo: '03.png', title: 'On accompagne\nles restaurants\nà devenir des\nréférences.', sub: 'Sur la durée. Chaque semaine, chez vous.\nVision · Suisse romande · Un restaurant par cuisine, par ville.'},
	{kind: 'statement', kicker: 'Le constat', photo: '10.png', title: 'Un bon restaurant que\npersonne ne connaît reste\nun bon restaurant vide.', body: 'À 19h, vos futurs clients décident où ils vont manger, téléphone en main. Si votre salle n’est pas sur leur écran à ce moment-là, ils vont ailleurs.\n\nNotre travail, c’est l’inverse.'},
	{kind: 'numbers', kicker: 'Résultats', items: [{big: '×3', label: 'clients en moins de 90 jours chez les restaurants qu’on accompagne'}, {big: '+50 %', label: 'de chiffre d’affaires sur la même période'}, {big: '500 000', label: 'personnes touchées en Suisse romande'}], note: 'Dernier restaurant accompagné, Fribourg : 12 000 personnes touchées en 30 jours, portée ×16, visites de profil ×6, clics ×10. Résultats constatés en salle et sur les comptes des restaurants accompagnés.'},
	{kind: 'steps', kicker: 'L’accompagnement', title: 'Pas une fois.\nChaque semaine, chez vous.', steps: [{n: '01', t: 'On comprend votre restaurant', d: 'Votre cuisine, votre salle, votre quartier, ce qui fait venir et ce qui fait revenir. On pose le positionnement avant de sortir une caméra.'}, {n: '02', t: 'On tourne chez vous, régulièrement', d: 'Plusieurs fois par mois. Le vrai service, sans mise en scène. Vous ne fermez pas, vous ne jouez rien.'}, {n: '03', t: 'On publie, on mesure, on ajuste', d: 'Chaque semaine, un seul interlocuteur. On suit ce qui remplit la salle et on pousse ce qui marche.'}, {n: '04', t: 'On fait grandir le restaurant avec vous', d: 'La salle pleine en semaine, une équipe fière, une adresse qu’on recommande. Le seul chiffre qui compte se lit dans votre salle.'}]},
	{kind: 'statement', kicker: 'Rentabilité', photo: '19.png', title: 'Rentable dès\nle premier mois.', body: 'Chez les restaurants qu’on accompagne : +50 % de chiffre d’affaires, ×3 clients en moins de 90 jours.\n\nCe qu’on coûte revient en couverts. L’accompagnement se finance lui-même, le reste est pour vous. C’est pour ça qu’on travaille sur la durée, pas au coup par coup.'},
	{kind: 'photos', kicker: 'Ce qu’on montre', photos: ['07.png', '19.png', '17.png', '12.png', '08.png', '18.png']},
	{kind: 'statement', kicker: 'Votre app', photo: '09.png', title: 'Vous voyez tout.\nVous validez tout.', body: 'Votre app Vision : les tournages planifiés chez vous, chaque vidéo à valider avant publication, vos résultats en direct.\n\nOn s’occupe de tout, vous gardez la main sur tout. Et on se voit plusieurs fois par mois, chez vous.'},
	{kind: 'statement', kicker: 'Exclusivité', photo: '05.png', title: 'Un restaurant par cuisine,\npar ville.', body: 'On n’accompagne jamais deux restaurants de la même cuisine dans la même ville. Votre croissance, votre quartier, vos clients : on ne les partage avec personne.\n\nLe premier qui signe garde la place.'},
	{kind: 'offer', kicker: 'Investissement', title: 'Ce que comprend\nl’accompagnement.', lines: ['Stratégie et positionnement de votre restaurant', 'Tournages réguliers chez vous, plusieurs fois par mois', 'Vidéos courtes montées, publiées, suivies chaque semaine', 'Suivi des résultats et ajustements, mois après mois', 'Exclusivité sur votre cuisine dans votre ville', 'Un seul interlocuteur, réponse en 24 heures', 'Votre app : tournages, validation des vidéos, résultats en direct'], price: '1 890.–', cta: 'Votre place est-elle libre ? · @vision.agency · visionmedia-agency.com'},
];
